# MkDocs Configuration

site_name: SEL_RDB Documentation
site_description: Technical documentation for SEL_RDB, a Python package for analyzing and creating SEL relay database files.
site_author: AOUF Nihed

repo_url: https://github.com/AoufNihed/SEL_Rdb
repo_name: AoufNihed/SEL_Rdb

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Usage Examples: usage.md
  - API Reference: api.md
  - Contributing: contributing.md
  - License: license.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html